server:
  port: 4005
spring:
  cloud:
    gateway:
      routes:
        - id: customer-service-route
          uri: http://pb-customer-service:4000
          predicates:
            - Path=/api/customers/**
          filters:
            - StripPrefix=1
            - JwtValidation

#        - id: billing-service-route
#          uri: http://billing-service:4001
#          predicates:
#            - Path=/api/billing/**
#          filters:
#            - StripPrefix=1

        - id: auth-service-route
          uri: http://pb-auth-service:4002
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - JwtValidation
