### PUT request to update a customer info
PUT http://localhost:4000/customers/20ac18f4-60a6-4069-8cd9-a1e86aa13811
Content-Type: application/json

{
  "name": "Popesc24u Ion",
  "email": "myPopIoon@yahoo.com",
  "address": "newAddress"
}
###