### Login request for user authentication

POST http://localhost:4002/login
Content-Type: application/json

{
  "email": "testuser@test.com",
  "password": "password123"
}

### Login request for user authentication through api-gateway
POST http://localhost:4005/auth/login
Content-Type: application/json

{
"email": "testuser@test.com",
"password": "password123"
}

> {% client.global.set("token", response.body.token) %}
