name: Service Coverage

on:
  push:
    branches:
      - main

jobs:
  report-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test customer-service
        run: |
          cd customer-service
          mvn clean verify

      - name: Extract customer-service  test coverage using PowerShell
        id: coverage
        shell: pwsh
        run: |
          $htmlFile = "customer-service/target/site/jacoco/index.html"

          if (-not (Test-Path $htmlFile)) {
            Write-Host "HTML file not found."
            "coverage=0" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
            exit 0
          }

          $htmlContent = Get-Content $htmlFile -Raw

          if ($htmlContent -match '<td>\s*Total\s*</td>\s*<td class="bar">.*?</td>\s*<td class="ctr2">(\d+)%</td>') {
            $coveragePercentage = $matches[1]
          } else {
            $coveragePercentage = 0
          }

          "coverage=$coveragePercentage" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Post coverage to GitHub Issue
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/3/comments \
            -d "{\"body\": \"Customer Service test coverage after latest push: **${{ steps.coverage.outputs.coverage }}%**\"}"
          
